spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          forecastResults-in: 
            destinations: forecastResults
            contentType: application/json
          forecastData-out:
            destinations: forecastData
            contentType: application/json